### ISSUE TITLE
Examples / Demos

### ISSUE THREAD

**Issue by vwochnik** [kyleshevlin/shevy#10]
Hello there! I love this SASS library and I am using it for three sites.
I have recommended it to be added to [Famolus/awesome-scss](https://github.com/Famolus/awesome-scss), but they said it is lacking a demo and examples.

I see you have a GitHub Page for this project. Why don't you add this to the README and project description? On top, you could add vertical lines to the page to show the correctness of the vertical rhythm.

I'm just suggesting this as appearing in one of those `awesome-*` lists gives a lot of traffic and stars.

**Comment by kyleshevlin** [comment]
Hey Vincent, I appreciate the support of the project. I can add some more examples and demos. Shouldn't be a problem.

**Comment by kyleshevlin** [comment]
Just leaving this as a note. Spent a good chunk of time on it the last 2 days and have made a big update to the Project Page. Examples are still pending.

I think I'm going to make a number of examples on CodePen and embed them so that users can see how easy it is to implement and be able to tweak the code.

**Comment by vwochnik** [comment]
Why don't you put them into an `examples` directory?

**Comment by vwochnik** [comment]
I've looked at the project page! Great work. But definitely keep the examples on that page also!

**Comment by kyleshevlin** [comment]
I decided to just go with making a few examples under the `examples/` directory as you suggested. I would have enjoyed users being able to test out the code right there in a Pen, but it seemed to be too much of a hassle to get working. There are now 4 examples and documentation at the Project Page website. I will make some updates in the future, but I'll consider this issue closed for now. Thanks.
