### ISSUE TITLE
i might be missing something

### ISSUE THREAD

**Issue by checktravis** [kyleshevlin/shevy#4]
I found your repo on the blog comments here http://www.zell-weekeat.com/responsive-typography

I like that your lib seems so much more simple to use, but when I look at your demo page I dont see the font or line space changing for different devices. I am using the emulator in google chrome to test.

**Comment by kyleshevlin** [comment]
I think you're missing something. The bottom most section is the one that uses two typography maps. They change font sizes at 540px wide. For example, below that breakpoint, the h1 font-size is 32px, and above that font-size the h1 font-size is 4.5em, which shows that the kind of mathematics used can be changed for the same typography.

Below 540px:
<img width="1677" alt="screen shot 2016-01-31 at 11 25 10 pm" src="https://cloud.githubusercontent.com/assets/4333144/12711121/137fef10-c872-11e5-8477-d98a12f97363.png">

Above 540px:
<img width="1676" alt="screen shot 2016-01-31 at 11 25 54 pm" src="https://cloud.githubusercontent.com/assets/4333144/12711122/13803600-c872-11e5-997a-f1303c7227c6.png">

**Comment by kyleshevlin** [comment]
I would also like to add that by responsive typography, I simply mean being able to redefine your font-scale per breakpoint. I never intended Shevy to dynamically adjust font-sizes via the browser width, though techniques exist using vw units to try that.
