### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by strarsis** [kyleshevlin/shevy#9]
It would be very helpful if this module is also published on npm.

**Comment by kyleshevlin** [comment]
Sure, I hadn't needed it for that yet because I was using Bower, but I believe Ember is trying to get away from using bower_components altogether, so making this an npm module isn't a bad idea. Thanks for the idea.

**Comment by kyleshevlin** [comment]
Published: https://www.npmjs.com/package/shevy

I'll be honest, I just followed the npm documentation on publishing, and didn't do anything to the repo whatsoever. If anyone finds some bugs with installing it via npm, please make an issue and we'll go from there.
